---
kind: Secret
apiVersion: v1
metadata:
  name: sno-dsc-all-pull-secret
  namespace: clusters
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    hypershift.openshift.io/safe-to-delete-with-cluster: "true"
data:
  .dockerconfigjson: >-
    <PULL_SECRET | base64encode>
type: kubernetes.io/dockerconfigjson
