---
apiVersion: hypershift.openshift.io/v1beta1
kind: HostedCluster
metadata:
  name: sno-dsc-all
  namespace: clusters
  labels:
    hypershift.openshift.io/auto-created-for-infra: sno-dsc-all
  annotations:
    argocd.argoproj.io/sync-wave: "30"
    cluster.open-cluster-management.io/clusterset: 'develop'
spec:
  autoscaling: {}
  configuration: {}
  controllerAvailabilityPolicy: SingleReplica
  dns:
    baseDomain: sandbox2969.opentlc.com
  etcd:
    managed:
      storage:
        persistentVolume:
          size: 8Gi
          storageClassName: gp3-csi
        type: PersistentVolume
    managementType: Managed
  fips: false
  infraID: sno-dsc-all
  infrastructureAvailabilityPolicy: SingleReplica
  issuerURL: https://hcp-clusters.s3.us-east-2.amazonaws.com/sno-dsc-all
  networking:
    clusterNetwork:
    - cidr: 10.132.0.0/14
    machineNetwork:
    - cidr: 10.0.0.0/16
    networkType: OVNKubernetes
    serviceNetwork:
    - cidr: 172.31.0.0/16
  olmCatalogPlacement: management
  platform:
    aws:
      cloudProviderConfig:
        zone: us-east-2b
      endpointAccess: Public
      region: us-east-2
    type: AWS
  pullSecret:
    name: sno-dsc-all-pull-secret
  release:
    image: quay.io/openshift-release-dev/ocp-release:4.15.13-multi
  secretEncryption:
    aescbc:
      activeKey:
        name: sno-dsc-all-etcd-encryption-key
    type: aescbc
  services:
  - service: APIServer
    servicePublishingStrategy:
      type: LoadBalancer
  - service: OAuthServer
    servicePublishingStrategy:
      type: Route
  - service: Konnectivity
    servicePublishingStrategy:
      type: Route
  - service: Ignition
    servicePublishingStrategy:
      type: Route
  - service: OVNSbDb
    servicePublishingStrategy:
      type: Route
  sshKey:
    name: sno-dsc-all-ssh-key
