---
apiVersion: hypershift.openshift.io/v1beta1
kind: NodePool
metadata:
  creationTimestamp: null
  name: sno-dsc-all-us-east-2b
  namespace: clusters
spec:
  arch: amd64
  clusterName: sno-dsc-all
  management:
    autoRepair: false
    upgradeType: Replace
  nodeDrainTimeout: 0s
  platform:
    aws:
      instanceProfile: sno-dsc-all-worker
      instanceType: g6.4xlarge
      rootVolume:
        size: 200
        type: gp3
      securityGroups:
      - id: sg-042e3c4800e174b0d
      subnet:
        id: subnet-0e5e16a0a0273562b
    type: AWS
  release:
    image: quay.io/openshift-release-dev/ocp-release:4.15.13-multi
  replicas: 1
