---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: vault
  namespace: openshift-gitops
spec:
  goTemplate: true
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: placement-hub-openshift
        requeueAfterSeconds: 180
  syncPolicy:
    preserveResourcesOnDeletion: false
  template:
    metadata:
      name: assisted-service-{{.name}}
      annotations:
        argocd.argoproj.io/compare-options: IgnoreExtraneous
    spec:
      project: default
      destination:
        server: "{{.server}}"
        namespace: vault
      source:
        repoURL: https://github.com/eformat/sno-hcp-rhoai.git
        path: gitops/applications/vault
        plugin:
          name: argocd-novault-plugin-helm
          env:
            - name: HELM_VALUES
              value: |
                vault.server.route.host=vault.apps.hub.sandbox2969.opentlc.com
                vault.server.extraEnvironmentVars.VAULT_TLS_SERVER_NAME=vault.apps.hub.sandbox2969.opentlc.com
        targetRevision: main
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
