---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: policy-collection-sno-dsc-all
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/eformat/sno-hcp-rhoai.git
    path: policy-collection/overlays/sno-dsc-all
    targetRevision: main
    plugin:
      name: argocd-vault-plugin-kustomize
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
