---
apiVersion: hypershift.openshift.io/v1beta1
kind: NodePool
metadata:
  creationTimestamp: null
  name: rainforest-us-east-2c
  namespace: clusters
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  arch: amd64
  clusterName: rainforest
  config:
  - name: rainforest-machineconfig
  management:
    autoRepair: false
    upgradeType: Replace
  nodeDrainTimeout: 0s
  platform:
    aws:
      instanceProfile: rainforest-worker
      instanceType: g6.8xlarge
      rootVolume:
        size: 200
        type: gp3
      securityGroups:
      - id: sg-00b8949f7f814d1e0
      subnet:
        id: subnet-0d2735eae6780691c
    type: AWS
  release:
    image: quay.io/openshift-release-dev/ocp-release:4.15.15-multi
  replicas: 1
