---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: sno-dsc-all
  namespace: openshift-gitops
spec:
  goTemplate: true
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: placement-hub-openshift
        requeueAfterSeconds: 180
  syncPolicy:
    preserveResourcesOnDeletion: true
  template:
    metadata:
      name: sno-dsc-all-{{.name}}
      annotations:
        argocd.argoproj.io/compare-options: IgnoreExtraneous
    spec:
      project: default
      destination:
        server: "{{.server}}"
        namespace: openshift-gitops
      source:
        repoURL: https://github.com/eformat/sno-hcp-rhoai.git
        path: gitops/applications/managed-clusters/sno-dsc-all
        targetRevision: main
        plugin:
          name: argocd-vault-plugin-kustomize
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
