---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: certificates-sno-dsc-all
  namespace: openshift-gitops
spec:
  goTemplate: true
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: placement-sno-dsc-all
        requeueAfterSeconds: 180
  syncPolicy:
    preserveResourcesOnDeletion: false
  template:
    metadata:
      name: certificates-sno-dsc-all-{{.name}}
      annotations:
        argocd.argoproj.io/compare-options: IgnoreExtraneous
    spec:
      project: default
      destination:
        server: "{{.server}}"
        namespace: openshift-gitops
      source:
        repoURL: https://github.com/eformat/sno-hcp-rhoai.git
        path: gitops/applications/certificates
        targetRevision: main
        plugin:
          name: argocd-novault-plugin-kustomize
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
