---
apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: gpu-sno-dsc-all
placementBindingDefaults:
  name: gpu-sno-dsc-all
policyDefaults:
  placement:
    placementName: placement-sno-dsc-all
  categories:
    - CM Configuration Management
  complianceType: "musthave"
  controls:
    - CM-2 Baseline Configuration
  consolidateManifests: false
  copyPolicyMetadata: false
  disabled: false
  namespace: openshift-gitops
  pruneObjectBehavior: "DeleteIfCreated"
  remediationAction: enforce
  severity: medium
  standards:
    - NIST SP 800-53
  policyAnnotations: {"argocd.argoproj.io/compare-options": "IgnoreExtraneous"}
policies:
  - name: gpu-sno-dsc-all
    manifests:
      - path: input/
