---
apiVersion: policy.open-cluster-management.io/v1beta1
kind: PolicySet
metadata:
  name: rainforest-cluster
spec:
  description: "Policies for cluster configuration"
  policies:
    - cluster-admin-rainforest
    - label-node-rainforest
    - console-plugins-rainforest
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-rainforest-cluster
placementRef:
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
  name: placement-rainforest
subjects:
  - apiGroup: policy.open-cluster-management.io
    kind: PolicySet
    name: rainforest-cluster
